# syntax=docker.io/docker/dockerfile:1
# Source https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

FROM node:24

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_LOGFLARE_API_TOKEN=$NEXT_PUBLIC_LOGFLARE_API_TOKEN
ENV NEXT_PUBLIC_LOGFLARE_CLIENT_TOKEN=$NEXT_PUBLIC_LOGFLARE_CLIENT_TOKEN
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASSWORD=$SMTP_PASSWORD

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci --ignore-scripts

COPY frontend/ .

RUN npm run build

COPY start.sh .

RUN chmod +x start.sh

EXPOSE 3000

CMD ["./start.sh"]
