#!/bin/sh

echo "Generating window.env config..."

cat <<EOF > ./public/env.js
window.env = {
  NEXT_PUBLIC_SUPABASE_URL: "$NEXT_PUBLIC_SUPABASE_URL",
  NEXT_PUBLIC_LOGFLARE_CLIENT_TOKEN: "$NEXT_PUBLIC_LOGFLARE_CLIENT_TOKEN",
  NEXT_PUBLIC_LOGFLARE_API_TOKEN: "$NEXT_PUBLIC_LOGFLARE_API_TOKEN",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "$NEXT_PUBLIC_SUPABASE_ANON_KEY",
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: "$NEXT_PUBLIC_TURNSTILE_SITE_KEY",
  NEXT_PUBLIC_SITE_URL: "$NEXT_PUBLIC_SITE_URL"
};
EOF

echo "Config generated."
echo "Starting Next.js..."

exec npm start
