name: 'database-tests'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          OUTPUT=$(supabase start)

          NEXT_PUBLIC_SUPABASE_URL=$(echo "$OUTPUT" | grep 'API URL' | cut -d ':' -f2)
          NEXT_PUBLIC_SUPABASE_ANON_KEY=$(echo "$OUTPUT" | grep 'anon key' | cut -d ':' -f2)
          SUPABASE_SERVICE_ROLE_KEY=$(echo "$OUTPUT" | grep ' service_role key' | cut -d ':' -f2)

          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY" >> $GITHUB_ENV
      - run: supabase db lint
      - run: supabase test db
      - run: npm ci
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend
      - run: |
          nohup npm start -- --port 3000 > next.log 2>&1 &
        working-directory: ./frontend
      - run: npx --yes wait-on http://localhost:3000
